In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import classification_report , accuracy_score

### syntheses the data 

In [8]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_features=10, 
    n_samples=1000, 
    n_informative=8,
    n_redundant=2,
    n_repeated=0,
    n_classes=2, 
    random_state=42
)


In [11]:
df_x  = pd.DataFrame(X)
df_x

0         1         2         3         4         5         6  \
0   -0.224515 -0.648598  2.805591  0.569525  2.676771  0.685312  0.306675   
1    1.038548 -1.316803  2.303387  1.233593  4.972675  1.086905 -3.548788   
2    1.148988  1.794382  2.835693 -1.114858 -1.247120 -1.899268 -0.381470   
3   -1.177318  2.420294 -0.363514 -1.086646 -2.824750 -2.722123 -0.225266   
4    1.346717  0.089373  2.056613 -0.428365  0.285387  1.140716  0.721945   
..        ...       ...       ...       ...       ...       ...       ...   
995 -2.520259  0.866810 -1.258367 -0.051690 -3.178799 -2.773020  1.006616   
996  0.200395  3.244450 -3.193443  0.222183 -5.098802 -1.758987  1.097709   
997 -2.912178  0.281646 -1.480678  0.950130 -0.419412 -2.504918 -1.824500   
998  0.276948  1.802273 -0.541781 -2.593740 -4.243454 -0.708498 -1.371959   
999 -0.095247  3.336626  1.466282  2.448995  0.480969 -1.897929 -2.768536   

            7         8         9  
0    1.147291 -2.145905  2.477879  
1    0.342810 -0.469005  2.787109  
2    0.837209  0.163223 -0.997959  
3    0.515079 -3.317272 -2.801517  
4    1.110152  2.426608  0.880496  
..        ...       ...       ...  
995 -1.380548 -1.018613 -2.322042  
996  1.312274  1.198744 -4.314869  
997  0.122025 -4.838295 -1.104499  
998  4.125930 -0.308262 -2.752850  
999  0.327730  2.036008 -1.989216  

[1000 rows x 10 columns]

In [12]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

#### Logestic Rgression

In [13]:
log_model = LogisticRegression()

log_model.fit(X_train ,y_train)

y_predict_log  = log_model.predict(X_test)

print(classification_report(y_predict_log , y_test))

              precision    recall  f1-score   support

           0       0.62      0.73      0.67        91
           1       0.73      0.63      0.68       109

    accuracy                           0.68       200
   macro avg       0.68      0.68      0.67       200
weighted avg       0.68      0.68      0.68       200



### lets use kfold and look how is the score

In [17]:
from sklearn.model_selection import KFold

kf  = KFold(n_splits = 5 , shuffle = False , random_state = None)


    print(train_index , test_index)



[1 2 3 4] [0]
[0 2 3 4] [1]
[0 1 3 4] [2]
[0 1 2 4] [3]
[0 1 2 3] [4]


### yeah lets use KFold in logisticRegression

In [24]:
l_model  = LogisticRegression()
accuracy_array = []

for train_index , test_index in kf.split(X , y):
    X_train , X_test = X[train_index] , X[test_index]
    y_train , y_test = y[train_index] , y[test_index]

    l_model.fit(X_train , y_train)
    y_predict_l = l_model.predict(X_test)

    accuracy_array.append(l_model.score(X_test , y_test))

    report = classification_report(y_predict_l , y_test)

accuracy_array

    

    

[0.7, 0.7, 0.655, 0.69, 0.695]

### Cross validation on Logistic Regression

In [30]:
from sklearn.model_selection import cross_val_score

result = cross_val_score(LogisticRegression() , X , y , cv = kf , scoring  = "accuracy")
print(result)

[0.7   0.7   0.655 0.69  0.695]


### Cross validation on DecisionTreeClassifier

In [29]:
from sklearn.model_selection import cross_val_score

result = cross_val_score(DecisionTreeClassifier() , X , y , cv = kf , scoring  = "accuracy")
print(result)

[0.77  0.78  0.81  0.835 0.805]


### Cross validation on RandomForestClassifier

In [32]:

from sklearn.model_selection import cross_val_score

result = cross_val_score(RandomForestClassifier() , X , y , cv = kf , scoring  = "accuracy")
print(result)

[0.885 0.885 0.91  0.91  0.895]
